[tools]
bun = "1.3.8"
rust = { version = "1.93.0", targets = "thumbv7em-none-eabihf" }

# firmware development
"nix:usbutils" = "018"
"nix:probe-rs-tools" = "0.31.0"

"nix:gcc" = "15.2.0" # rust dependency

[plugins]
nix = "https://github.com/jbadeau/mise-nix"
