[tools]
rust = { version = "1.93.0", profile = "default", targets = "thumbv7em-none-eabihf" }
"nix:usbutils" = "018"
"nix:probe-rs-tools" = "0.31.0"

# indirect dependencies
"nix:gcc" = "15.2.0" # rust dependency

[plugins]
nix = "https://github.com/jbadeau/mise-nix"
