on:
  push:
    paths:
      - docs/**
  pull_request:
    paths:
      - docs/**
  workflow_dispatch:

name: Docs CI
jobs:
  ci:
    name: Docs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v4
        with:
          version: 10.23.0 # synced with devenv

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.11.1 # synced with devenv
          cache: pnpm
          cache-dependency-path: docs/pnpm-lock.yaml

      - run: cd docs && pnpm install

      - run: cd docs && pnpm build
