on:
  push:
    paths:
      - docs/**
  pull_request:
    paths:
      - docs/**
  workflow_dispatch:

name: Docs CI
jobs:
  ci:
    name: Docs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - run: cd docs && bun install --frozen-lockfile

      - run: cd docs && bun run build
