on:
  push:
    paths:
      - docs/**
  pull_request:
    paths:
      - docs/**
  workflow_dispatch:

name: Docs CI
jobs:
  ci:
    name: Docs CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v3
        with:
          experimental: true
          working_directory: docs

      - run: bun install --frozen-lockfile
        working-directory: docs

      - run: bun run build
        working-directory: docs
