on:
  push:
    paths:
      - firmware/**
  pull_request:
    paths:
      - firmware/**
  workflow_dispatch:

name: Firmware CI
jobs:
  ci:
    name: Firmware CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - run: rustup target add thumbv7em-none-eabihf

      - run: cd firmware && cargo check

      - run: cd firmware && cargo clippy -- -W clippy::pedantic

      - run: cd firmware && cargo fmt --all -- --check

      # todo: re-enable when there are stuff to test
      # - run: cd firmware && cargo test

      - run: cd firmware && cargo build --release
