on:
  push:
    paths:
      - firmware/**
  pull_request:
    paths:
      - firmware/**
  workflow_dispatch:

name: Firmware CI
jobs:
  ci:
    name: Firmware CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: jdx/mise-action@v3
        with:
          experimental: true
          working_directory: firmware

      - run: rustup target add thumbv7em-none-eabihf

      - run: rustup component add clippy

      - run: rustup component add rustfmt

      - run: cargo check
        working-directory: firmware

      - run: cargo clippy -- -W clippy::pedantic
        working-directory: firmware

      - run: cargo fmt --all -- --check
        working-directory: firmware

      # todo: re-enable when there are stuff to test
      # - run: cargo test
      #   working-directory: firmware

      - run: cargo build --release
        working-directory: firmware
