on:
  push:
    paths:
      - web/**
  pull_request:
    paths:
      - web/**
  workflow_dispatch:

name: Web CI
jobs:
  ci:
    name: Web CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: jdx/mise-action@v3
        with:
          experimental: true
          working_directory: web

      - run: bun install --frozen-lockfile
        working-directory: web

      - run: bun run lint
        working-directory: web

      - name: Create .env file
        run: cp ./web/.env.local.example ./web/.env.local

      - run: bun run build:frontend
        working-directory: web

      - run: bunx prettier -l .
        working-directory: web
