on:
  push:
    paths:
      - web/**
  pull_request:
    paths:
      - web/**
  workflow_dispatch:

name: Web CI
jobs:
  ci:
    name: Web CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - run: cd web && bun install --frozen-lockfile

      - run: cd web && bun run lint

      - name: Create .env file
        run: cp ./web/.env.local.example ./web/.env.local

      - run: cd web && bun run build:frontend
