on:
  push:
    paths:
      - web/**
  pull_request:
    paths:
      - web/**
  workflow_dispatch:

name: Web CI
jobs:
  ci:
    name: Web CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # see https://devenv.sh/integrations/github-actions/
      - uses: cachix/install-nix-action@v26
      - uses: cachix/cachix-action@v14
        with:
          name: devenv
      - name: Install devenv.sh
        run: nix profile install nixpkgs#devenv

      - run: cd web && pnpm lint
        shell: devenv shell bash -- -e {0}

      - run: cd web && pnpm build
        shell: devenv shell bash -- -e {0}

      - run: cd web && pnpm prettier -l .
        shell: devenv shell bash -- -e {0}
