on:
  push:
    paths:
      - web/**
  pull_request:
    paths:
      - web/**
  workflow_dispatch:

name: Web CI
jobs:
  ci:
    name: Web CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # https://github.com/pnpm/action-setup
      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1 # synced with devenv

      # https://github.com/actions/setup-node
      - uses: actions/setup-node@v4
        with:
          node-version: 24.4.1 # synced with devenv
          cache: pnpm

      - run: cd web && pnpm install

      - run: cd web && pnpm lint

      - run: cd web && pnpm build

      - run: cd web && pnpm prettier -l .
