on:
  push:
  pull_request:
  workflow_dispatch:

name: Formatting check
jobs:
  ci:
    name: Formatting check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: cachix/install-nix-action@v31

      - uses: jdx/mise-action@v3
        with:
          experimental: true

      - run: bun install

      - run: bun run format
